contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #wgsratblab channel"
    url: https://nfcore.slack.com/channels/wgsratblab
    about: Discussion about the nf-core/wgsratblab pipeline
